### ISSUE TITLE
spec is not working when upgrading hanami-api latest version(0.1.1)

### ISSUE THREAD

**Issue by MasanoriOnishi** [jodosha/hanami-api-amazon-aws-lambda#2]
## Description
When I upgrade 'hanami-api' to lates version(0.1.1), spec is not working.

## Command

```
$ bundle update hanami-api
$ bundle exec rake
```

## Error
```
Failures:

  1) Request: GET /tracks/:id returns successful response
     Failure/Error: @app ||= App.new

     NameError:
       instance variable @url_helpers not defined
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:306:in `remove_instance_variable'
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:306:in `freeze'
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:299:in `initialize'
     # ./spec/spec_helper.rb:12:in `new'
     # ./spec/spec_helper.rb:12:in `app'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:30:in `build_rack_mock_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:26:in `rack_mock_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:41:in `build_rack_test_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:37:in `rack_test_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:45:in `current_session'
     # ./spec/requests/tracks_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) Request: GET / returns successful response
     Failure/Error: @app ||= App.new

     NameError:
       instance variable @url_helpers not defined
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:306:in `remove_instance_variable'
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:306:in `freeze'
     # ./vendor/bundle/ruby/2.7.0/gems/hanami-api-0.1.1/lib/hanami/api.rb:299:in `initialize'
     # ./spec/spec_helper.rb:12:in `new'
     # ./spec/spec_helper.rb:12:in `app'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:30:in `build_rack_mock_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:26:in `rack_mock_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:41:in `build_rack_test_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:37:in `rack_test_session'
     # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/methods.rb:45:in `current_session'
     # ./spec/requests/index_spec.rb:5:in `block (2 levels) in <top (required)>'

Top 3 slowest examples (0.01021 seconds, 69.0% of total time):
  Request: POST /tracks returns successful response
    0.00994 seconds ./spec/requests/tracks_spec.rb:13
  Request: GET /tracks/:id returns successful response
    0.00017 seconds ./spec/requests/tracks_spec.rb:4
  Request: GET / returns successful response
    0.0001 seconds ./spec/requests/index_spec.rb:4

Top 3 slowest example groups:
  Request: POST /tracks
    0.0103 seconds average (0.0103 seconds / 1 example) ./spec/requests/tracks_spec.rb:12
  Request: GET /tracks/:id
    0.00037 seconds average (0.00037 seconds / 1 example) ./spec/requests/tracks_spec.rb:3
  Request: GET /
    0.00024 seconds average (0.00024 seconds / 1 example) ./spec/requests/index_spec.rb:3

Finished in 0.0148 seconds (files took 0.21682 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/requests/tracks_spec.rb:4 # Request: GET /tracks/:id returns successful response
rspec ./spec/requests/index_spec.rb:4 # Request: GET / returns successful response

Randomized with seed 24032
```

**Comment by MasanoriOnishi** [comment]
@jodosha 
Probably this fix seems to affect the bug.

https://github.com/hanami/api/commit/3dbbbf324393ff233711cf78459226382a093af4#diff-4b4cbdafabdf5c3ec95b8cc2a030d879R304

**Comment by jodosha** [comment]
@MasanoriOnishi I've updated the deps (`hanami-api` is at `v0.1.2` now) and the specs are passing again.

**Comment by MasanoriOnishi** [comment]
@jodosha 
Thank you so much for your fix!!
